config/routes.rb
Rails.application.routes.draw do
  resources :trip_attachments

  get 'password_resets/new'

  get 'password_resets/edit'

  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'borrow'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users 
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :possessions,         only: [:create, :destroy, :edit]
  resources :trips
  resources :comments
  get 'search_trips', to: 'search_trips#search'
  get 'search_users', to: 'search_users#search'
  root                'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
This is a simple Ruby on Rails app written during my Computer Science studies at University of Wroclaw.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
If you have any questions contact me at <a href="mailto:ares_real@wp.pl">ares_real@wp.pl</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="center jumbotron">
    <h1>Welcome to the Trips Portal!</h1>

    <h2>
      This is the home page for the Trips Portal sample application.
    </h2>

    <%= link_to "Browse trips now!", trips_path, class: "btn btn-lg btn-primary" %>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Trips Portal!</h1>

    <h2>
      This is the home page for the Trips Portal sample application.
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

<% end %>