config/routes.rb
Rails.application.routes.draw do
  resources :trip_attachments

  get 'password_resets/new'

  get 'password_resets/edit'

  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'borrow'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users 
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :possessions,         only: [:create, :destroy, :edit]
  resources :trips
  resources :comments
  get 'search_trips', to: 'search_trips#search'
  get 'search_users', to: 'search_users#search'
  root                'static_pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :trip
  	belongs_to :user
	validates :trip_id,  presence: true
	validates :user_id, presence: true
	validates :text, presence: true
	validates :grade, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  	before_action :logged_in_user,     only: [:new, :update, :edit, :create, :destroy]
	
	def edit
    	@comment = Comment.find(params[:id])
    	@trip = Trip.find(@comment.trip_id)
  	end

  	def new
  		@trip = Trip.find(params[:id])
 		@comment = Comment.new
 	end

	def create
		@comment = Comment.new(comment_params)
		@trip = Trip.find(params[:comment][:trip_id])
		if @comment.save
		 	redirect_to @trip
		else
		 	 render 'new'
		end
	end

  	def destroy
    	@comment = Comment.find(params[:id])
    	@trip = Trip.find(@comment.trip_id)
    	@comment.destroy
    	flash[:success] = "Copy deleted"
    	redirect_to @trip
  	end

 	def update
		@comment = Comment.find(params[:id])
		@trip = Trip.find(@comment.trip_id)
		if @comment.update_attributes(comment_params)
	 	 	flash[:success] = "Copy updated"
	  		redirect_to @trip
		else
	  		redirect_to action: 'edit', id: params[:id]
		end
	end

	def admin_user
    	redirect_to(trips_url) unless logged_in? && current_user.admin?
  	end

	private

		    def comment_params
      			params.require(:comment).permit(:text, :user_id, :trip_id, :grade)
    		end

end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<tr>
          <td class="data"> <%= comment.text %> </td>
          <td class="data"> <%= comment.grade %></td> 
          <td class="data"> <%= User.find(comment.user.id).name %> <%= User.find(comment.user.id).surname %></td> 
          <td class="actions">
            <% if logged_in? %>
              <% if current_user.id == comment.user_id %>
                <%= link_to edit_comment_path(comment) do %>
                  <input type="button" value="Edit" class="btn btn-primary marginally_left"/>
                <% end %>
                <%= link_to comment_path(comment), :method => :delete do %>
                  <input type="button" value="Delete" class="btn btn-primary marginally_left"/>
                <% end %>
              <% end %>
            <% end %>
          </td>
</tr>

app/views/comments/edit.html.erb
<% provide(:title, "Edit a comment") %>
<h1>Update comment info</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@comment) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :text %>
      <%= f.text_area :text, class: 'form-control' %>

      <%= f.label :grade %>
      <%= f.number_field :grade, class: 'form-control' %>

      <%= f.hidden_field :user_id, :value => current_user.id %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/comments/new.html.erb
<% provide(:title, "Create a comment") %>
<h1>Create comment</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@comment) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>


      <%= f.label :text %>
      <%= f.text_area :text, class: 'form-control' %>

      <%= f.label :grade %>
      <%= f.number_field :grade, class: 'form-control' %>

      <%= f.hidden_field :trip_id, :value => params[:id] %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.submit "Save new comment", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>