config/routes.rb
Rails.application.routes.draw do
  resources :trip_attachments

  get 'password_resets/new'

  get 'password_resets/edit'

  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'borrow'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users 
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :possessions,         only: [:create, :destroy, :edit]
  resources :trips
  resources :comments
  get 'search_trips', to: 'search_trips#search'
  get 'search_users', to: 'search_users#search'
  root                'static_pages#home'

end

app/models/trip_attachment.rb
class TripAttachment < ActiveRecord::Base
   mount_uploader :avatar, AvatarUploader
   belongs_to :trip
end

app/controllers/trip_attachments_controller.rb
class TripAttachmentsController < ApplicationController
  before_action :set_trip_attachment, only: [:show, :edit, :update, :destroy]

  # GET /trip_attachments
  # GET /trip_attachments.json
  def index
    @trip_attachments = TripAttachment.all
  end

  # GET /trip_attachments/1
  # GET /trip_attachments/1.json
  def show
  end

  # GET /trip_attachments/new
  def new
    @trip_attachment = TripAttachment.new
  end
  # GET /trip_attachments/1/edit
  def edit
    @trip_attachment = TripAttachment.find(params[:id])
    @trip = @trip_attachment.trip
    @trip_attachment.destroy
    redirect_to trip_path(@trip) 
  end

  # POST /trip_attachments
  # POST /trip_attachments.json
  def create
    @trip_attachment = TripAttachment.new(trip_attachment_params)

    respond_to do |format|
      if @trip_attachment.save
        format.html { redirect_to @trip_attachment, notice: 'Trip attachment was successfully created.' }
        format.json { render :show, status: :created, location: @trip_attachment }
      else
        format.html { render :new }
        format.json { render json: @trip_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trip_attachments/1
  # PATCH/PUT /trip_attachments/1.json
  def update
    respond_to do |format|
      if @trip_attachment.update(trip_attachment_params)
        format.html { redirect_to @trip_attachment.trip, notice: 'Post attachment was successfully updated.' }
      end 
    end
  end

  # DELETE /trip_attachments/1
  # DELETE /trip_attachments/1.json
  def destroy
    @trip_attachment.destroy
    respond_to do |format|
      format.html { redirect_to trip_attachments_url, notice: 'Trip attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip_attachment
      @trip_attachment = TripAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_attachment_params
      params.require(:trip_attachment).permit(:trip_id, :avatar)
    end
end

app/helpers/trip_attachments_helper.rb
module TripAttachmentsHelper
end

app/views/trip_attachments/_form.html.erb
<%= image_tag @trip_attachment.avatar %>
<%= form_for(@trip_attachment) do |f| %>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trip_attachments/edit.html.erb
<h1>Editing Trip Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip_attachment %> |
<%= link_to 'Back', trip_attachments_path %>

app/views/trip_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trip Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Trip</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trip_attachments.each do |trip_attachment| %>
      <tr>
        <td><%= trip_attachment.trip_id %></td>
        <td><%= trip_attachment.avatar %></td>
        <td><%= link_to 'Show', trip_attachment %></td>
        <td><%= link_to 'Edit', edit_trip_attachment_path(trip_attachment) %></td>
        <td><%= link_to 'Destroy', trip_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip attachment', new_trip_attachment_path %>

app/views/trip_attachments/new.html.erb
<h1>New Trip Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', trip_attachments_path %>

app/views/trip_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Trip:</strong>
  <%= @trip_attachment.trip_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @trip_attachment.avatar %>
</p>

<%= link_to 'Edit', edit_trip_attachment_path(@trip_attachment) %> |
<%= link_to 'Back', trip_attachments_path %>