config/routes.rb
Rails.application.routes.draw do
  resources :trip_attachments

  get 'password_resets/new'

  get 'password_resets/edit'

  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'borrow'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users 
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :possessions,         only: [:create, :destroy, :edit]
  resources :trips
  resources :comments
  get 'search_trips', to: 'search_trips#search'
  get 'search_users', to: 'search_users#search'
  root                'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom" style="background-color: white;">
  <small>
    The Trips Portal
    by Arkadiusz Krawczyk
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed-top">
    <nav>
      <ul id="navigation">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Trips", trips_path %></li>
        <li><%= link_to "Search trips", search_trips_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "Users", users_path %></li>
          
          <% end %>
          <% if current_user.admin? %>
            <li><%= link_to "Search users", search_users_path %></li>
          <% end %>
          <li class="dropdown" style="text-align: center;">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>